site_name: CS479 Machine Learning for 3D Data (KAIST, Fall 2023)

theme:
  name: material
  icon:
    logo: material/cube-outline
  features:
    - navigation.tabs
    - navigation.tabs.sticky

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - attr_list
  - footnotes
  - meta
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - tables

plugins:
  - macros

copyright: Copyright &copy; 2023 Minhyuk Sung

nav:
  - Home: index.md
  - Programming Assignments: programming-assignments.md
  - Paper Review: paper-review.md
  - Project:
    - Project Team Matching: project-team-matching.md
    - Project Proposal: project-proposal.md
    - Project Tracks: project-tracks.md
    - Project Mockup: project-mockup.md
    - Project Pitch Video: project-pitch-video.md
    - Project Interim Report: project-interim-report.md
    - Project Submission Guidelines: project-submission-guidelines.md
    - Poster Session Guidelines: poster-session-guidelines.md
    - Project Review Guidelines: project-review-guidelines.md
  - Guest Lectures:
    - Niloy J. Mitra: guest-lecture-niloy-mitra.md
    - Jun Gao: guest-lecture-jun-gao.md

extra:
  analytics:
    provider: google
    property: G-S3GEPQ874N
  links:
    paper_list: https://docs.google.com/spreadsheets/d/1i-C6Ao4mrXnVqj0AKnTfS0AB6hd8SpEuB3JI1JZgKbI/edit?usp=sharing
    pitch_videos: https://youtu.be/gW9MiQJSfzg
    poster_template: https://kaistackr-my.sharepoint.com/:p:/g/personal/mhsung_kaist_ac_kr/EaAxelUapjBMrWQ1qcUwsAIBo24eSmN2QvuuN3y0Y3jc7A?e=sl7v4l
    lec01: https://kaistackr-my.sharepoint.com/:b:/g/personal/mhsung_kaist_ac_kr/EXPl933tZ9BItoZdMeJyuHwByUNJLCP1nNWdZ-muOxPadA?e=XcxmSR
    lec02: https://kaistackr-my.sharepoint.com/:b:/g/personal/mhsung_kaist_ac_kr/EROv07NTwj9Fonaz3CZUmfMBHsP6VManKqHwAeGTdXuwdQ?e=slbVJr
    lec03: https://kaistackr-my.sharepoint.com/:b:/g/personal/mhsung_kaist_ac_kr/EQiHg0GE8qZDuji_XAfGgS0BoA6aXZstPsDTAYDs5pNLHw?e=peXQXK
    lec04: https://kaistackr-my.sharepoint.com/:b:/g/personal/mhsung_kaist_ac_kr/EU7Gy2aM4JZEmaD-hv0wffkBX6TpYaXk5Jq6KTNpVdY4bA?e=MalZFJ
    lec05: https://kaistackr-my.sharepoint.com/:b:/g/personal/mhsung_kaist_ac_kr/EcUsLOLibAdGpqjpI1tIaUEBAPaSOgH7_vH5D6Zvu7b5eA?e=B4V7bG
    lec06: https://kaistackr-my.sharepoint.com/:b:/g/personal/mhsung_kaist_ac_kr/EQc9ZJ0sVtVBv4gw2v3lUMwBqow1TtD0VM8xesHmzFjnxg?e=nN2GN3
    lec07: https://kaistackr-my.sharepoint.com/:b:/g/personal/mhsung_kaist_ac_kr/ETLaY6j9B69Fn6kgMizYJisBgsZf6nqPIyWSMWxRfMrBeg?e=JurRje
    lec08: https://kaistackr-my.sharepoint.com/:b:/g/personal/mhsung_kaist_ac_kr/EXW4CPpkMYNBm6QwVqaF8NQBI25Rfqn_r01wLVlri-NIRw?e=wTEMpx
    lec09: https://kaistackr-my.sharepoint.com/:b:/g/personal/mhsung_kaist_ac_kr/EVl7o7oqv6dFmTVvyna_YcMBLK3qY4mcVXOdi8ZOrroGWA?e=g3odVN
    lec12: https://kaistackr-my.sharepoint.com/:b:/g/personal/mhsung_kaist_ac_kr/EfMgda84qHlBlFLZE6o7JdUB2NyAUXdFDZRLKnbkCD0lBQ?e=MXJsae
    lec14: https://kaistackr-my.sharepoint.com/:b:/g/personal/mhsung_kaist_ac_kr/ETUpY-RwpHFBiAuGHz3lopwBm0gdcp62PIH8S3TOxgsedA?e=pO7CTK
    lec15: https://kaistackr-my.sharepoint.com/:b:/g/personal/mhsung_kaist_ac_kr/Ef4M-rbuQh5Ag5Q6vny-E7UBhWUkCwFLJ419iW00KQ39Dw?e=PXig7d
    lec16: https://kaistackr-my.sharepoint.com/:b:/g/personal/mhsung_kaist_ac_kr/ERaaYVVLs3JLp2-0EtkTfo4B3mOY0oyn-zvWE5IYqVqSbQ?e=PJNaVm
    lec17: https://kaistackr-my.sharepoint.com/:b:/g/personal/mhsung_kaist_ac_kr/EYc4eX8NqeFNqN2Ea1CcBs8BXUGKQbcL4axBGHjJwWzTPA?e=8m5roZ
    lec18: https://kaistackr-my.sharepoint.com/:b:/g/personal/mhsung_kaist_ac_kr/EdMvV2bIb4pJnbhS6hiicAcB3fW2-rK9eQSyquI5Wlq3Vg?e=Vojz2Q
    lec19: https://kaistackr-my.sharepoint.com/:b:/g/personal/mhsung_kaist_ac_kr/EfL7dlIVUoVNkVTXWVcEwZABetNf_JQbBFJaIacUeu4lrg?e=sL3Sel
    rec01: https://youtu.be/ghGk3HcxUgg
    rec02: https://youtu.be/933wv8i3QKU
    rec03: https://youtu.be/i04fhF9fOdM
    rec04: https://youtu.be/p3eWGEUYkwM
    rec05: https://youtu.be/kyFX7T_Wma8
    rec06: https://youtu.be/_7z9YWSF0QE
    rec07: https://youtu.be/psvsLo8xcjI
    rec08: https://youtu.be/mx5TLGxe5u4
    rec09: https://youtu.be/a_LK04UKSXk
    rec10: https://youtu.be/UcYGymBWDzA
    rec12: https://youtu.be/n2QzSzdAxN0
    rec13: https://youtu.be/_u5dqkOyABY
    rec14: https://youtu.be/lFMhAUsrGCM
    rec15: https://youtu.be/lgsO5bYHpRU
    rec16: https://youtu.be/At8TmqQqCUE
    rec17: https://youtu.be/UAhgd9PGSes
    rec18: https://youtu.be/fyRvS1QT2i4
    rec19: https://youtu.be/lo8Gdv4rm88
