site_name: CSML000 Machine Learning Course

theme:
  font:
    text: Roboto
  name: material
  icon:
    logo: material/cube-outline
    repo: fontawesome/brands/github
  features:
    - navigation.tabs
    - navigation.tabs.sticky


repo_url: https://github.com/nthaihoc/iast-csml000

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - attr_list
  - footnotes
  - meta
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - tables

plugins:
  - macros

copyright: Copyright by Thai Hoc Nguyen

nav:
  - Home: index.md
   - Resource: programming-assignments.md 
   - Datasets: paper-review.md
   - Project:
     - Project Team Matching: project-team-matching.md
     - Project Proposal: project-proposal.md
     - Project Tracks: project-tracks.md
     - Project Mockup: project-mockup.md
     - Project Pitch Video: project-pitch-video.md
     - Project Interim Report: project-interim-report.md
     - Project Submission Guidelines: project-submission-guidelines.md
     - Poster Session Guidelines: poster-session-guidelines.md
     - Project Review Guidelines: project-review-guidelines.md
   - Guest Lectures:
     - Niloy J. Mitra: guest-lecture-niloy-mitra.md
     - Jun Gao: guest-lecture-jun-gao.md

extra:
  analytics:
    provider: google
    property: G-S3GEPQ874N
  links:
    lec02: https://drive.google.com/drive/folders/1-pePMyNJuVEXeTV1Nq1zQpGTNm0K3MGo?usp=drive_link
    code02: https://www.kaggle.com/code/nguyenthaihoc/01-linear-regression-gradient-descent
