site_name: CSML000 Machine Learning Course (IAST-2024)

theme:
  name: material
  icon:
    logo: material/cube-outline
  features:
    - navigation.tabs
    - navigation.tabs.sticky

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - attr_list
  - footnotes
  - meta
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - tables

plugins:
  - macros

copyright: Copyright &copy; 2023 Minhyuk Sung

nav:
  - Home: index.md
  # - Programming Assignments: programming-assignments.md
  # - Paper Review: paper-review.md
  # - Project:
  #   - Project Team Matching: project-team-matching.md
  #   - Project Proposal: project-proposal.md
  #   - Project Tracks: project-tracks.md
  #   - Project Mockup: project-mockup.md
  #   - Project Pitch Video: project-pitch-video.md
  #   - Project Interim Report: project-interim-report.md
  #   - Project Submission Guidelines: project-submission-guidelines.md
  #   - Poster Session Guidelines: poster-session-guidelines.md
  #   - Project Review Guidelines: project-review-guidelines.md
  # - Guest Lectures:
  #   - Niloy J. Mitra: guest-lecture-niloy-mitra.md
  #   - Jun Gao: guest-lecture-jun-gao.md

extra:
  analytics:
    provider: google
    property: G-S3GEPQ874N
  links:
    paper_list: https://docs.google.com/spreadsheets/d/1i-C6Ao4mrXnVqj0AKnTfS0AB6hd8SpEuB3JI1JZgKbI/edit?usp=sharing
    pitch_videos: https://youtu.be/gW9MiQJSfzg
    poster_template: https://kaistackr-my.sharepoint.com/:p:/g/personal/mhsung_kaist_ac_kr/EaAxelUapjBMrWQ1qcUwsAIBo24eSmN2QvuuN3y0Y3jc7A?e=sl7v4l
    lec01: 
    code01: 
